/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressRouteImport } from './routes/account.address'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCatalogueRouteImport } from './routes/dashboard/catalogue'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardPickupPointsRouteImport } from './routes/dashboard/pickup-points'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as RecapsSlugRouteImport } from './routes/recaps.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffPickupRouteImport } from './routes/staff.pickup'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAvatarsUserIdRouteImport } from './routes/api/avatars.$userId'
import { Route as ApiCatalogueImagesImageIdRouteImport } from './routes/api/catalogue-images.$imageId'
import { Route as DashboardCatalogueIndexRouteImport } from './routes/dashboard/catalogue.index'
import { Route as DashboardCatalogueSlugRouteImport } from './routes/dashboard/catalogue.$slug'
import { Route as DashboardCatalogueNewRouteImport } from './routes/dashboard/catalogue.new'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events.index'
import { Route as DashboardEventsSlugRouteImport } from './routes/dashboard/events.$slug'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard/events.new'
import { Route as DashboardFinanceIndexRouteImport } from './routes/dashboard/finance.index'
import { Route as DashboardFinanceExpensesRouteImport } from './routes/dashboard/finance.expenses'
import { Route as DashboardFinanceIncomeRouteImport } from './routes/dashboard/finance.income'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders.index'
import { Route as DashboardOrdersIdRouteImport } from './routes/dashboard/orders.$id'
import { Route as DashboardPickupPointsIndexRouteImport } from './routes/dashboard/pickup-points.index'
import { Route as DashboardPickupPointsIdRouteImport } from './routes/dashboard/pickup-points.$id'
import { Route as DashboardPickupPointsNewRouteImport } from './routes/dashboard/pickup-points.new'
import { Route as DashboardRolesIndexRouteImport } from './routes/dashboard/roles.index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users.index'
import { Route as DashboardUsersIdRouteImport } from './routes/dashboard/users.$id'
import { Route as EventsSlugIndexRouteImport } from './routes/events.$slug.index'
import { Route as EventsSlugPaymentRouteImport } from './routes/events.$slug.payment'
import { Route as EventsSlugRegisterRouteImport } from './routes/events.$slug.register'
import { Route as ShopCheckoutIndexRouteImport } from './routes/shop.checkout.index'
import { Route as ShopCheckoutCancelRouteImport } from './routes/shop.checkout.cancel'
import { Route as ShopCheckoutReturnRouteImport } from './routes/shop.checkout.return'
import { Route as ShopCheckoutSimulateRouteImport } from './routes/shop.checkout.simulate'
import { Route as ApiPaymentsWebhookProviderRouteImport } from './routes/api/payments.webhook.$provider'
import { Route as DashboardEventsSlugIndexRouteImport } from './routes/dashboard/events.$slug.index'
import { Route as DashboardEventsSlugCategoriesRouteImport } from './routes/dashboard/events.$slug.categories'
import { Route as DashboardEventsSlugEditRouteImport } from './routes/dashboard/events.$slug.edit'
import { Route as DashboardEventsSlugGroupsRouteImport } from './routes/dashboard/events.$slug.groups'
import { Route as DashboardEventsSlugPromosRouteImport } from './routes/dashboard/events.$slug.promos'
import { Route as EventsSlugPaymentSimulateRouteImport } from './routes/events.$slug.payment.simulate'
import { Route as DashboardEventsSlugParticipantsParticipantIdRouteImport } from './routes/dashboard/events.$slug.participants.$participantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressRoute = AccountAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCatalogueRoute = DashboardCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPickupPointsRoute = DashboardPickupPointsRouteImport.update({
  id: '/pickup-points',
  path: '/pickup-points',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const RecapsSlugRoute = RecapsSlugRouteImport.update({
  id: '/recaps/$slug',
  path: '/recaps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPickupRoute = StaffPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => StaffRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarsUserIdRoute = ApiAvatarsUserIdRouteImport.update({
  id: '/api/avatars/$userId',
  path: '/api/avatars/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogueImagesImageIdRoute =
  ApiCatalogueImagesImageIdRouteImport.update({
    id: '/api/catalogue-images/$imageId',
    path: '/api/catalogue-images/$imageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCatalogueIndexRoute = DashboardCatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCatalogueRoute,
} as any)
const DashboardCatalogueSlugRoute = DashboardCatalogueSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardCatalogueRoute,
} as any)
const DashboardCatalogueNewRoute = DashboardCatalogueNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardCatalogueRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardEventsSlugRoute = DashboardEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFinanceRoute,
} as any)
const DashboardFinanceExpensesRoute =
  DashboardFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => DashboardFinanceRoute,
  } as any)
const DashboardFinanceIncomeRoute = DashboardFinanceIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => DashboardFinanceRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const DashboardOrdersIdRoute = DashboardOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const DashboardPickupPointsIndexRoute =
  DashboardPickupPointsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPickupPointsRoute,
  } as any)
const DashboardPickupPointsIdRoute = DashboardPickupPointsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardPickupPointsRoute,
} as any)
const DashboardPickupPointsNewRoute =
  DashboardPickupPointsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardPickupPointsRoute,
  } as any)
const DashboardRolesIndexRoute = DashboardRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRolesRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugPaymentRoute = EventsSlugPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugRegisterRoute = EventsSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsSlugRoute,
} as any)
const ShopCheckoutIndexRoute = ShopCheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopCheckoutRoute,
} as any)
const ShopCheckoutCancelRoute = ShopCheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ShopCheckoutRoute,
} as any)
const ShopCheckoutReturnRoute = ShopCheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => ShopCheckoutRoute,
} as any)
const ShopCheckoutSimulateRoute = ShopCheckoutSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => ShopCheckoutRoute,
} as any)
const ApiPaymentsWebhookProviderRoute =
  ApiPaymentsWebhookProviderRouteImport.update({
    id: '/api/payments/webhook/$provider',
    path: '/api/payments/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEventsSlugIndexRoute =
  DashboardEventsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any)
const DashboardEventsSlugCategoriesRoute =
  DashboardEventsSlugCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any)
const DashboardEventsSlugEditRoute = DashboardEventsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardEventsSlugRoute,
} as any)
const DashboardEventsSlugGroupsRoute =
  DashboardEventsSlugGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any)
const DashboardEventsSlugPromosRoute =
  DashboardEventsSlugPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any)
const EventsSlugPaymentSimulateRoute =
  EventsSlugPaymentSimulateRouteImport.update({
    id: '/simulate',
    path: '/simulate',
    getParentRoute: () => EventsSlugPaymentRoute,
  } as any)
const DashboardEventsSlugParticipantsParticipantIdRoute =
  DashboardEventsSlugParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/account/address': typeof AccountAddressRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/catalogue': typeof DashboardCatalogueRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/pickup-points': typeof DashboardPickupPointsRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/recaps/$slug': typeof RecapsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRouteWithChildren
  '/staff/pickup': typeof StaffPickupRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$userId': typeof ApiAvatarsUserIdRoute
  '/api/catalogue-images/$imageId': typeof ApiCatalogueImagesImageIdRoute
  '/dashboard/catalogue/$slug': typeof DashboardCatalogueSlugRoute
  '/dashboard/catalogue/new': typeof DashboardCatalogueNewRoute
  '/dashboard/events/$slug': typeof DashboardEventsSlugRouteWithChildren
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/finance/expenses': typeof DashboardFinanceExpensesRoute
  '/dashboard/finance/income': typeof DashboardFinanceIncomeRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/pickup-points/$id': typeof DashboardPickupPointsIdRoute
  '/dashboard/pickup-points/new': typeof DashboardPickupPointsNewRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/events/$slug/payment': typeof EventsSlugPaymentRouteWithChildren
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/shop/checkout/cancel': typeof ShopCheckoutCancelRoute
  '/shop/checkout/return': typeof ShopCheckoutReturnRoute
  '/shop/checkout/simulate': typeof ShopCheckoutSimulateRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/dashboard/catalogue/': typeof DashboardCatalogueIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/pickup-points/': typeof DashboardPickupPointsIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/shop/checkout/': typeof ShopCheckoutIndexRoute
  '/api/payments/webhook/$provider': typeof ApiPaymentsWebhookProviderRoute
  '/dashboard/events/$slug/categories': typeof DashboardEventsSlugCategoriesRoute
  '/dashboard/events/$slug/edit': typeof DashboardEventsSlugEditRoute
  '/dashboard/events/$slug/groups': typeof DashboardEventsSlugGroupsRoute
  '/dashboard/events/$slug/promos': typeof DashboardEventsSlugPromosRoute
  '/events/$slug/payment/simulate': typeof EventsSlugPaymentSimulateRoute
  '/dashboard/events/$slug/': typeof DashboardEventsSlugIndexRoute
  '/dashboard/events/$slug/participants/$participantId': typeof DashboardEventsSlugParticipantsParticipantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/address': typeof AccountAddressRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/recaps/$slug': typeof RecapsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/staff/pickup': typeof StaffPickupRoute
  '/account': typeof AccountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/staff': typeof StaffIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$userId': typeof ApiAvatarsUserIdRoute
  '/api/catalogue-images/$imageId': typeof ApiCatalogueImagesImageIdRoute
  '/dashboard/catalogue/$slug': typeof DashboardCatalogueSlugRoute
  '/dashboard/catalogue/new': typeof DashboardCatalogueNewRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/finance/expenses': typeof DashboardFinanceExpensesRoute
  '/dashboard/finance/income': typeof DashboardFinanceIncomeRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/pickup-points/$id': typeof DashboardPickupPointsIdRoute
  '/dashboard/pickup-points/new': typeof DashboardPickupPointsNewRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/events/$slug/payment': typeof EventsSlugPaymentRouteWithChildren
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/shop/checkout/cancel': typeof ShopCheckoutCancelRoute
  '/shop/checkout/return': typeof ShopCheckoutReturnRoute
  '/shop/checkout/simulate': typeof ShopCheckoutSimulateRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/dashboard/catalogue': typeof DashboardCatalogueIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/finance': typeof DashboardFinanceIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/pickup-points': typeof DashboardPickupPointsIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/shop/checkout': typeof ShopCheckoutIndexRoute
  '/api/payments/webhook/$provider': typeof ApiPaymentsWebhookProviderRoute
  '/dashboard/events/$slug/categories': typeof DashboardEventsSlugCategoriesRoute
  '/dashboard/events/$slug/edit': typeof DashboardEventsSlugEditRoute
  '/dashboard/events/$slug/groups': typeof DashboardEventsSlugGroupsRoute
  '/dashboard/events/$slug/promos': typeof DashboardEventsSlugPromosRoute
  '/events/$slug/payment/simulate': typeof EventsSlugPaymentSimulateRoute
  '/dashboard/events/$slug': typeof DashboardEventsSlugIndexRoute
  '/dashboard/events/$slug/participants/$participantId': typeof DashboardEventsSlugParticipantsParticipantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/account/address': typeof AccountAddressRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/catalogue': typeof DashboardCatalogueRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/pickup-points': typeof DashboardPickupPointsRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/recaps/$slug': typeof RecapsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRouteWithChildren
  '/staff/pickup': typeof StaffPickupRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$userId': typeof ApiAvatarsUserIdRoute
  '/api/catalogue-images/$imageId': typeof ApiCatalogueImagesImageIdRoute
  '/dashboard/catalogue/$slug': typeof DashboardCatalogueSlugRoute
  '/dashboard/catalogue/new': typeof DashboardCatalogueNewRoute
  '/dashboard/events/$slug': typeof DashboardEventsSlugRouteWithChildren
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/finance/expenses': typeof DashboardFinanceExpensesRoute
  '/dashboard/finance/income': typeof DashboardFinanceIncomeRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/pickup-points/$id': typeof DashboardPickupPointsIdRoute
  '/dashboard/pickup-points/new': typeof DashboardPickupPointsNewRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/events/$slug/payment': typeof EventsSlugPaymentRouteWithChildren
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/shop/checkout/cancel': typeof ShopCheckoutCancelRoute
  '/shop/checkout/return': typeof ShopCheckoutReturnRoute
  '/shop/checkout/simulate': typeof ShopCheckoutSimulateRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/dashboard/catalogue/': typeof DashboardCatalogueIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/pickup-points/': typeof DashboardPickupPointsIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/shop/checkout/': typeof ShopCheckoutIndexRoute
  '/api/payments/webhook/$provider': typeof ApiPaymentsWebhookProviderRoute
  '/dashboard/events/$slug/categories': typeof DashboardEventsSlugCategoriesRoute
  '/dashboard/events/$slug/edit': typeof DashboardEventsSlugEditRoute
  '/dashboard/events/$slug/groups': typeof DashboardEventsSlugGroupsRoute
  '/dashboard/events/$slug/promos': typeof DashboardEventsSlugPromosRoute
  '/events/$slug/payment/simulate': typeof EventsSlugPaymentSimulateRoute
  '/dashboard/events/$slug/': typeof DashboardEventsSlugIndexRoute
  '/dashboard/events/$slug/participants/$participantId': typeof DashboardEventsSlugParticipantsParticipantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/account'
    | '/events'
    | '/shop'
    | '/staff'
    | '/account/address'
    | '/account/orders'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/catalogue'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/orders'
    | '/dashboard/pickup-points'
    | '/dashboard/roles'
    | '/dashboard/users'
    | '/events/$slug'
    | '/recaps/$slug'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/checkout'
    | '/staff/pickup'
    | '/account/'
    | '/dashboard/'
    | '/events/'
    | '/shop/'
    | '/staff/'
    | '/account/orders/$id'
    | '/api/auth/$'
    | '/api/avatars/$userId'
    | '/api/catalogue-images/$imageId'
    | '/dashboard/catalogue/$slug'
    | '/dashboard/catalogue/new'
    | '/dashboard/events/$slug'
    | '/dashboard/events/new'
    | '/dashboard/finance/expenses'
    | '/dashboard/finance/income'
    | '/dashboard/orders/$id'
    | '/dashboard/pickup-points/$id'
    | '/dashboard/pickup-points/new'
    | '/dashboard/users/$id'
    | '/events/$slug/payment'
    | '/events/$slug/register'
    | '/shop/checkout/cancel'
    | '/shop/checkout/return'
    | '/shop/checkout/simulate'
    | '/account/orders/'
    | '/dashboard/catalogue/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/orders/'
    | '/dashboard/pickup-points/'
    | '/dashboard/roles/'
    | '/dashboard/users/'
    | '/events/$slug/'
    | '/shop/checkout/'
    | '/api/payments/webhook/$provider'
    | '/dashboard/events/$slug/categories'
    | '/dashboard/events/$slug/edit'
    | '/dashboard/events/$slug/groups'
    | '/dashboard/events/$slug/promos'
    | '/events/$slug/payment/simulate'
    | '/dashboard/events/$slug/'
    | '/dashboard/events/$slug/participants/$participantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/address'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/recaps/$slug'
    | '/shop/$slug'
    | '/shop/cart'
    | '/staff/pickup'
    | '/account'
    | '/dashboard'
    | '/events'
    | '/shop'
    | '/staff'
    | '/account/orders/$id'
    | '/api/auth/$'
    | '/api/avatars/$userId'
    | '/api/catalogue-images/$imageId'
    | '/dashboard/catalogue/$slug'
    | '/dashboard/catalogue/new'
    | '/dashboard/events/new'
    | '/dashboard/finance/expenses'
    | '/dashboard/finance/income'
    | '/dashboard/orders/$id'
    | '/dashboard/pickup-points/$id'
    | '/dashboard/pickup-points/new'
    | '/dashboard/users/$id'
    | '/events/$slug/payment'
    | '/events/$slug/register'
    | '/shop/checkout/cancel'
    | '/shop/checkout/return'
    | '/shop/checkout/simulate'
    | '/account/orders'
    | '/dashboard/catalogue'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/orders'
    | '/dashboard/pickup-points'
    | '/dashboard/roles'
    | '/dashboard/users'
    | '/events/$slug'
    | '/shop/checkout'
    | '/api/payments/webhook/$provider'
    | '/dashboard/events/$slug/categories'
    | '/dashboard/events/$slug/edit'
    | '/dashboard/events/$slug/groups'
    | '/dashboard/events/$slug/promos'
    | '/events/$slug/payment/simulate'
    | '/dashboard/events/$slug'
    | '/dashboard/events/$slug/participants/$participantId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/account'
    | '/events'
    | '/shop'
    | '/staff'
    | '/account/address'
    | '/account/orders'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/catalogue'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/orders'
    | '/dashboard/pickup-points'
    | '/dashboard/roles'
    | '/dashboard/users'
    | '/events/$slug'
    | '/recaps/$slug'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/checkout'
    | '/staff/pickup'
    | '/account/'
    | '/dashboard/'
    | '/events/'
    | '/shop/'
    | '/staff/'
    | '/account/orders/$id'
    | '/api/auth/$'
    | '/api/avatars/$userId'
    | '/api/catalogue-images/$imageId'
    | '/dashboard/catalogue/$slug'
    | '/dashboard/catalogue/new'
    | '/dashboard/events/$slug'
    | '/dashboard/events/new'
    | '/dashboard/finance/expenses'
    | '/dashboard/finance/income'
    | '/dashboard/orders/$id'
    | '/dashboard/pickup-points/$id'
    | '/dashboard/pickup-points/new'
    | '/dashboard/users/$id'
    | '/events/$slug/payment'
    | '/events/$slug/register'
    | '/shop/checkout/cancel'
    | '/shop/checkout/return'
    | '/shop/checkout/simulate'
    | '/account/orders/'
    | '/dashboard/catalogue/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/orders/'
    | '/dashboard/pickup-points/'
    | '/dashboard/roles/'
    | '/dashboard/users/'
    | '/events/$slug/'
    | '/shop/checkout/'
    | '/api/payments/webhook/$provider'
    | '/dashboard/events/$slug/categories'
    | '/dashboard/events/$slug/edit'
    | '/dashboard/events/$slug/groups'
    | '/dashboard/events/$slug/promos'
    | '/events/$slug/payment/simulate'
    | '/dashboard/events/$slug/'
    | '/dashboard/events/$slug/participants/$participantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  RecapsSlugRoute: typeof RecapsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarsUserIdRoute: typeof ApiAvatarsUserIdRoute
  ApiCatalogueImagesImageIdRoute: typeof ApiCatalogueImagesImageIdRoute
  ApiPaymentsWebhookProviderRoute: typeof ApiPaymentsWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/address': {
      id: '/account/address'
      path: '/address'
      fullPath: '/account/address'
      preLoaderRoute: typeof AccountAddressRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalogue': {
      id: '/dashboard/catalogue'
      path: '/catalogue'
      fullPath: '/dashboard/catalogue'
      preLoaderRoute: typeof DashboardCatalogueRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pickup-points': {
      id: '/dashboard/pickup-points'
      path: '/pickup-points'
      fullPath: '/dashboard/pickup-points'
      preLoaderRoute: typeof DashboardPickupPointsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/recaps/$slug': {
      id: '/recaps/$slug'
      path: '/recaps/$slug'
      fullPath: '/recaps/$slug'
      preLoaderRoute: typeof RecapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/pickup': {
      id: '/staff/pickup'
      path: '/pickup'
      fullPath: '/staff/pickup'
      preLoaderRoute: typeof StaffPickupRouteImport
      parentRoute: typeof StaffRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatars/$userId': {
      id: '/api/avatars/$userId'
      path: '/api/avatars/$userId'
      fullPath: '/api/avatars/$userId'
      preLoaderRoute: typeof ApiAvatarsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalogue-images/$imageId': {
      id: '/api/catalogue-images/$imageId'
      path: '/api/catalogue-images/$imageId'
      fullPath: '/api/catalogue-images/$imageId'
      preLoaderRoute: typeof ApiCatalogueImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/catalogue/': {
      id: '/dashboard/catalogue/'
      path: '/'
      fullPath: '/dashboard/catalogue/'
      preLoaderRoute: typeof DashboardCatalogueIndexRouteImport
      parentRoute: typeof DashboardCatalogueRoute
    }
    '/dashboard/catalogue/$slug': {
      id: '/dashboard/catalogue/$slug'
      path: '/$slug'
      fullPath: '/dashboard/catalogue/$slug'
      preLoaderRoute: typeof DashboardCatalogueSlugRouteImport
      parentRoute: typeof DashboardCatalogueRoute
    }
    '/dashboard/catalogue/new': {
      id: '/dashboard/catalogue/new'
      path: '/new'
      fullPath: '/dashboard/catalogue/new'
      preLoaderRoute: typeof DashboardCatalogueNewRouteImport
      parentRoute: typeof DashboardCatalogueRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/events/$slug': {
      id: '/dashboard/events/$slug'
      path: '/$slug'
      fullPath: '/dashboard/events/$slug'
      preLoaderRoute: typeof DashboardEventsSlugRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/finance/': {
      id: '/dashboard/finance/'
      path: '/'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/finance/expenses': {
      id: '/dashboard/finance/expenses'
      path: '/expenses'
      fullPath: '/dashboard/finance/expenses'
      preLoaderRoute: typeof DashboardFinanceExpensesRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/finance/income': {
      id: '/dashboard/finance/income'
      path: '/income'
      fullPath: '/dashboard/finance/income'
      preLoaderRoute: typeof DashboardFinanceIncomeRouteImport
      parentRoute: typeof DashboardFinanceRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard/orders/$id': {
      id: '/dashboard/orders/$id'
      path: '/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard/pickup-points/': {
      id: '/dashboard/pickup-points/'
      path: '/'
      fullPath: '/dashboard/pickup-points/'
      preLoaderRoute: typeof DashboardPickupPointsIndexRouteImport
      parentRoute: typeof DashboardPickupPointsRoute
    }
    '/dashboard/pickup-points/$id': {
      id: '/dashboard/pickup-points/$id'
      path: '/$id'
      fullPath: '/dashboard/pickup-points/$id'
      preLoaderRoute: typeof DashboardPickupPointsIdRouteImport
      parentRoute: typeof DashboardPickupPointsRoute
    }
    '/dashboard/pickup-points/new': {
      id: '/dashboard/pickup-points/new'
      path: '/new'
      fullPath: '/dashboard/pickup-points/new'
      preLoaderRoute: typeof DashboardPickupPointsNewRouteImport
      parentRoute: typeof DashboardPickupPointsRoute
    }
    '/dashboard/roles/': {
      id: '/dashboard/roles/'
      path: '/'
      fullPath: '/dashboard/roles/'
      preLoaderRoute: typeof DashboardRolesIndexRouteImport
      parentRoute: typeof DashboardRolesRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/dashboard/users/$id': {
      id: '/dashboard/users/$id'
      path: '/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/payment': {
      id: '/events/$slug/payment'
      path: '/payment'
      fullPath: '/events/$slug/payment'
      preLoaderRoute: typeof EventsSlugPaymentRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/register': {
      id: '/events/$slug/register'
      path: '/register'
      fullPath: '/events/$slug/register'
      preLoaderRoute: typeof EventsSlugRegisterRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/shop/checkout/': {
      id: '/shop/checkout/'
      path: '/'
      fullPath: '/shop/checkout/'
      preLoaderRoute: typeof ShopCheckoutIndexRouteImport
      parentRoute: typeof ShopCheckoutRoute
    }
    '/shop/checkout/cancel': {
      id: '/shop/checkout/cancel'
      path: '/cancel'
      fullPath: '/shop/checkout/cancel'
      preLoaderRoute: typeof ShopCheckoutCancelRouteImport
      parentRoute: typeof ShopCheckoutRoute
    }
    '/shop/checkout/return': {
      id: '/shop/checkout/return'
      path: '/return'
      fullPath: '/shop/checkout/return'
      preLoaderRoute: typeof ShopCheckoutReturnRouteImport
      parentRoute: typeof ShopCheckoutRoute
    }
    '/shop/checkout/simulate': {
      id: '/shop/checkout/simulate'
      path: '/simulate'
      fullPath: '/shop/checkout/simulate'
      preLoaderRoute: typeof ShopCheckoutSimulateRouteImport
      parentRoute: typeof ShopCheckoutRoute
    }
    '/api/payments/webhook/$provider': {
      id: '/api/payments/webhook/$provider'
      path: '/api/payments/webhook/$provider'
      fullPath: '/api/payments/webhook/$provider'
      preLoaderRoute: typeof ApiPaymentsWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/$slug/': {
      id: '/dashboard/events/$slug/'
      path: '/'
      fullPath: '/dashboard/events/$slug/'
      preLoaderRoute: typeof DashboardEventsSlugIndexRouteImport
      parentRoute: typeof DashboardEventsSlugRoute
    }
    '/dashboard/events/$slug/categories': {
      id: '/dashboard/events/$slug/categories'
      path: '/categories'
      fullPath: '/dashboard/events/$slug/categories'
      preLoaderRoute: typeof DashboardEventsSlugCategoriesRouteImport
      parentRoute: typeof DashboardEventsSlugRoute
    }
    '/dashboard/events/$slug/edit': {
      id: '/dashboard/events/$slug/edit'
      path: '/edit'
      fullPath: '/dashboard/events/$slug/edit'
      preLoaderRoute: typeof DashboardEventsSlugEditRouteImport
      parentRoute: typeof DashboardEventsSlugRoute
    }
    '/dashboard/events/$slug/groups': {
      id: '/dashboard/events/$slug/groups'
      path: '/groups'
      fullPath: '/dashboard/events/$slug/groups'
      preLoaderRoute: typeof DashboardEventsSlugGroupsRouteImport
      parentRoute: typeof DashboardEventsSlugRoute
    }
    '/dashboard/events/$slug/promos': {
      id: '/dashboard/events/$slug/promos'
      path: '/promos'
      fullPath: '/dashboard/events/$slug/promos'
      preLoaderRoute: typeof DashboardEventsSlugPromosRouteImport
      parentRoute: typeof DashboardEventsSlugRoute
    }
    '/events/$slug/payment/simulate': {
      id: '/events/$slug/payment/simulate'
      path: '/simulate'
      fullPath: '/events/$slug/payment/simulate'
      preLoaderRoute: typeof EventsSlugPaymentSimulateRouteImport
      parentRoute: typeof EventsSlugPaymentRoute
    }
    '/dashboard/events/$slug/participants/$participantId': {
      id: '/dashboard/events/$slug/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/dashboard/events/$slug/participants/$participantId'
      preLoaderRoute: typeof DashboardEventsSlugParticipantsParticipantIdRouteImport
      parentRoute: typeof DashboardEventsSlugRoute
    }
  }
}

interface DashboardCatalogueRouteChildren {
  DashboardCatalogueSlugRoute: typeof DashboardCatalogueSlugRoute
  DashboardCatalogueNewRoute: typeof DashboardCatalogueNewRoute
  DashboardCatalogueIndexRoute: typeof DashboardCatalogueIndexRoute
}

const DashboardCatalogueRouteChildren: DashboardCatalogueRouteChildren = {
  DashboardCatalogueSlugRoute: DashboardCatalogueSlugRoute,
  DashboardCatalogueNewRoute: DashboardCatalogueNewRoute,
  DashboardCatalogueIndexRoute: DashboardCatalogueIndexRoute,
}

const DashboardCatalogueRouteWithChildren =
  DashboardCatalogueRoute._addFileChildren(DashboardCatalogueRouteChildren)

interface DashboardEventsSlugRouteChildren {
  DashboardEventsSlugCategoriesRoute: typeof DashboardEventsSlugCategoriesRoute
  DashboardEventsSlugEditRoute: typeof DashboardEventsSlugEditRoute
  DashboardEventsSlugGroupsRoute: typeof DashboardEventsSlugGroupsRoute
  DashboardEventsSlugPromosRoute: typeof DashboardEventsSlugPromosRoute
  DashboardEventsSlugIndexRoute: typeof DashboardEventsSlugIndexRoute
  DashboardEventsSlugParticipantsParticipantIdRoute: typeof DashboardEventsSlugParticipantsParticipantIdRoute
}

const DashboardEventsSlugRouteChildren: DashboardEventsSlugRouteChildren = {
  DashboardEventsSlugCategoriesRoute: DashboardEventsSlugCategoriesRoute,
  DashboardEventsSlugEditRoute: DashboardEventsSlugEditRoute,
  DashboardEventsSlugGroupsRoute: DashboardEventsSlugGroupsRoute,
  DashboardEventsSlugPromosRoute: DashboardEventsSlugPromosRoute,
  DashboardEventsSlugIndexRoute: DashboardEventsSlugIndexRoute,
  DashboardEventsSlugParticipantsParticipantIdRoute:
    DashboardEventsSlugParticipantsParticipantIdRoute,
}

const DashboardEventsSlugRouteWithChildren =
  DashboardEventsSlugRoute._addFileChildren(DashboardEventsSlugRouteChildren)

interface DashboardEventsRouteChildren {
  DashboardEventsSlugRoute: typeof DashboardEventsSlugRouteWithChildren
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsSlugRoute: DashboardEventsSlugRouteWithChildren,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
)

interface DashboardFinanceRouteChildren {
  DashboardFinanceExpensesRoute: typeof DashboardFinanceExpensesRoute
  DashboardFinanceIncomeRoute: typeof DashboardFinanceIncomeRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
}

const DashboardFinanceRouteChildren: DashboardFinanceRouteChildren = {
  DashboardFinanceExpensesRoute: DashboardFinanceExpensesRoute,
  DashboardFinanceIncomeRoute: DashboardFinanceIncomeRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
}

const DashboardFinanceRouteWithChildren =
  DashboardFinanceRoute._addFileChildren(DashboardFinanceRouteChildren)

interface DashboardOrdersRouteChildren {
  DashboardOrdersIdRoute: typeof DashboardOrdersIdRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersIdRoute: DashboardOrdersIdRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardPickupPointsRouteChildren {
  DashboardPickupPointsIdRoute: typeof DashboardPickupPointsIdRoute
  DashboardPickupPointsNewRoute: typeof DashboardPickupPointsNewRoute
  DashboardPickupPointsIndexRoute: typeof DashboardPickupPointsIndexRoute
}

const DashboardPickupPointsRouteChildren: DashboardPickupPointsRouteChildren = {
  DashboardPickupPointsIdRoute: DashboardPickupPointsIdRoute,
  DashboardPickupPointsNewRoute: DashboardPickupPointsNewRoute,
  DashboardPickupPointsIndexRoute: DashboardPickupPointsIndexRoute,
}

const DashboardPickupPointsRouteWithChildren =
  DashboardPickupPointsRoute._addFileChildren(
    DashboardPickupPointsRouteChildren,
  )

interface DashboardRolesRouteChildren {
  DashboardRolesIndexRoute: typeof DashboardRolesIndexRoute
}

const DashboardRolesRouteChildren: DashboardRolesRouteChildren = {
  DashboardRolesIndexRoute: DashboardRolesIndexRoute,
}

const DashboardRolesRouteWithChildren = DashboardRolesRoute._addFileChildren(
  DashboardRolesRouteChildren,
)

interface DashboardUsersRouteChildren {
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteChildren: DashboardUsersRouteChildren = {
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteWithChildren = DashboardUsersRoute._addFileChildren(
  DashboardUsersRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardCatalogueRoute: typeof DashboardCatalogueRouteWithChildren
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren
  DashboardFinanceRoute: typeof DashboardFinanceRouteWithChildren
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardPickupPointsRoute: typeof DashboardPickupPointsRouteWithChildren
  DashboardRolesRoute: typeof DashboardRolesRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCatalogueRoute: DashboardCatalogueRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardFinanceRoute: DashboardFinanceRouteWithChildren,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardPickupPointsRoute: DashboardPickupPointsRouteWithChildren,
  DashboardRolesRoute: DashboardRolesRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressRoute: typeof AccountAddressRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressRoute: AccountAddressRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface EventsSlugPaymentRouteChildren {
  EventsSlugPaymentSimulateRoute: typeof EventsSlugPaymentSimulateRoute
}

const EventsSlugPaymentRouteChildren: EventsSlugPaymentRouteChildren = {
  EventsSlugPaymentSimulateRoute: EventsSlugPaymentSimulateRoute,
}

const EventsSlugPaymentRouteWithChildren =
  EventsSlugPaymentRoute._addFileChildren(EventsSlugPaymentRouteChildren)

interface EventsSlugRouteChildren {
  EventsSlugPaymentRoute: typeof EventsSlugPaymentRouteWithChildren
  EventsSlugRegisterRoute: typeof EventsSlugRegisterRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugPaymentRoute: EventsSlugPaymentRouteWithChildren,
  EventsSlugRegisterRoute: EventsSlugRegisterRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ShopCheckoutRouteChildren {
  ShopCheckoutCancelRoute: typeof ShopCheckoutCancelRoute
  ShopCheckoutReturnRoute: typeof ShopCheckoutReturnRoute
  ShopCheckoutSimulateRoute: typeof ShopCheckoutSimulateRoute
  ShopCheckoutIndexRoute: typeof ShopCheckoutIndexRoute
}

const ShopCheckoutRouteChildren: ShopCheckoutRouteChildren = {
  ShopCheckoutCancelRoute: ShopCheckoutCancelRoute,
  ShopCheckoutReturnRoute: ShopCheckoutReturnRoute,
  ShopCheckoutSimulateRoute: ShopCheckoutSimulateRoute,
  ShopCheckoutIndexRoute: ShopCheckoutIndexRoute,
}

const ShopCheckoutRouteWithChildren = ShopCheckoutRoute._addFileChildren(
  ShopCheckoutRouteChildren,
)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface StaffRouteChildren {
  StaffPickupRoute: typeof StaffPickupRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffPickupRoute: StaffPickupRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  RecapsSlugRoute: RecapsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarsUserIdRoute: ApiAvatarsUserIdRoute,
  ApiCatalogueImagesImageIdRoute: ApiCatalogueImagesImageIdRoute,
  ApiPaymentsWebhookProviderRoute: ApiPaymentsWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
